### ISSUE TITLE
I can't load the Website Access

### ISSUE THREAD

**Issue by Erisme** [tribalNerd/multisite-robotstxt-manager#7]
I can and i have successfully edit the robots.txt with the Network Access. 
But when i want to edit Website Admin > Settings Tab > MS Robots.txt Link.
I can't totaly load the Website Access. This is the same issue for all Website of my network.

<img width="1062" alt="capture d ecran 2019-01-27 a 11 26 45" src="https://user-images.githubusercontent.com/40033584/51803747-7c3d3b00-2226-11e9-97e9-aec7fd74d1c0.png">

**Comment by ChrisWinters** [comment]
Hello Erisme,
Not sure why I didn't see this months ago. Anyway, I am not sure what that problem was, however I assume that issue has been resolved. Please let me know though if you happen to still have that issue, if you're still using the plugin of course.

Thanks for taking the time to submit an issue even though I completely missed it some how.
